// Source: Plaid's Personal Finance Category (PFC) taxonomy, `personal_finance_category_version: 'v2'`.
// Verify against https://plaid.com/docs/api/products/transactions/#personal-finance-category-taxonomy
// whenever Plaid revises the taxonomy — this list is the single source of truth for onboarding
// category seeding (see onboardingService, Task 20).

export interface PfcMappingEntry {
  ledgeCategory: string
  /** Plaid's primary PFC code shared by every entry in detailedCodes, e.g. 'FOOD_AND_DRINK'. */
  primary: string
  color: string
  icon: string
  subcategories: string[]
  detailedCodes: string[]
}

export const DEFAULT_PFC_MAPPING: PfcMappingEntry[] = [
  {
    ledgeCategory: 'Food & Drink',
    primary: 'FOOD_AND_DRINK',
    color: '#F97316',
    icon: '🍽',
    subcategories: ['Restaurants', 'Groceries', 'Coffee', 'Bars'],
    detailedCodes: [
      'FOOD_AND_DRINK_RESTAURANTS',
      'FOOD_AND_DRINK_FAST_FOOD',
      'FOOD_AND_DRINK_GROCERIES',
      'FOOD_AND_DRINK_COFFEE',
      'FOOD_AND_DRINK_ALCOHOL_AND_BARS',
      'FOOD_AND_DRINK_FOOD_DELIVERY_SERVICES',
      'FOOD_AND_DRINK_VENDING_MACHINES',
      'FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK',
    ],
  },
  {
    ledgeCategory: 'Transport',
    primary: 'TRANSPORTATION',
    color: '#3B82F6',
    icon: '🚗',
    subcategories: ['Rideshare', 'Gas', 'Transit', 'Parking'],
    detailedCodes: [
      'TRANSPORTATION_TAXIS_AND_RIDE_SHARES',
      'TRANSPORTATION_GAS',
      'TRANSPORTATION_PUBLIC_TRANSIT',
      'TRANSPORTATION_PARKING',
      'TRANSPORTATION_TOLLS',
      'TRANSPORTATION_BIKES_AND_SCOOTERS',
      'TRANSPORTATION_OTHER_TRANSPORTATION',
    ],
  },
  {
    ledgeCategory: 'Travel',
    primary: 'TRAVEL',
    color: '#8B5CF6',
    icon: '✈️',
    subcategories: ['Flights', 'Hotels', 'Vacation'],
    detailedCodes: [
      'TRAVEL_FLIGHTS',
      'TRAVEL_LODGING',
      'TRAVEL_RENTAL_CARS',
      'TRAVEL_PARKING',
      'TRAVEL_OTHER_TRAVEL',
    ],
  },
  {
    ledgeCategory: 'Entertainment',
    primary: 'ENTERTAINMENT',
    color: '#EC4899',
    icon: '🎮',
    subcategories: ['Streaming', 'Events', 'Games'],
    detailedCodes: [
      'ENTERTAINMENT_MUSIC_AND_AUDIO',
      'ENTERTAINMENT_TV_AND_MOVIES',
      'ENTERTAINMENT_VIDEO_GAMES',
      'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS',
      'ENTERTAINMENT_CASINOS_AND_GAMBLING',
      'ENTERTAINMENT_OTHER_ENTERTAINMENT',
    ],
  },
  {
    ledgeCategory: 'Shopping',
    primary: 'GENERAL_MERCHANDISE',
    color: '#EAB308',
    icon: '🛍',
    subcategories: ['Clothing', 'Electronics', 'Amazon'],
    detailedCodes: [
      'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES',
      'GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES',
      'GENERAL_MERCHANDISE_ELECTRONICS',
      'GENERAL_MERCHANDISE_DEPARTMENT_STORES',
      'GENERAL_MERCHANDISE_DISCOUNT_STORES',
      'GENERAL_MERCHANDISE_PET_SUPPLIES',
      'GENERAL_MERCHANDISE_SPORTING_GOODS',
      'GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS',
      'GENERAL_MERCHANDISE_CONVENIENCE_STORES',
      'GENERAL_MERCHANDISE_TOBACCO_AND_VAPE',
      'GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES',
      'GENERAL_MERCHANDISE_OFFICE_SUPPLIES',
      'GENERAL_MERCHANDISE_SUPERSTORES',
      'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE',
    ],
  },
  {
    ledgeCategory: 'Bills & Utilities',
    primary: 'RENT_AND_UTILITIES',
    color: '#6B7280',
    icon: '🧾',
    subcategories: ['Rent', 'Electric', 'Internet', 'Phone'],
    detailedCodes: [
      'RENT_AND_UTILITIES_RENT',
      'RENT_AND_UTILITIES_GAS_AND_ELECTRICITY',
      'RENT_AND_UTILITIES_INTERNET_AND_CABLE',
      'RENT_AND_UTILITIES_TELEPHONE',
      'RENT_AND_UTILITIES_WATER',
      'RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT',
      'RENT_AND_UTILITIES_OTHER_UTILITIES',
    ],
  },
  {
    ledgeCategory: 'Health',
    primary: 'MEDICAL',
    color: '#10B981',
    icon: '⚕️',
    subcategories: ['Doctor', 'Pharmacy', 'Dental'],
    detailedCodes: [
      'MEDICAL_PRIMARY_CARE',
      'MEDICAL_DENTAL_CARE',
      'MEDICAL_EYE_CARE',
      'MEDICAL_NURSING_CARE',
      'MEDICAL_PHARMACIES_AND_SUPPLEMENTS',
      'MEDICAL_VETERINARY_SERVICES',
      'MEDICAL_OTHER_MEDICAL',
    ],
  },
  {
    ledgeCategory: 'Personal Care',
    primary: 'PERSONAL_CARE',
    color: '#F43F5E',
    icon: '💇',
    subcategories: ['Hair', 'Gym'],
    detailedCodes: [
      'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS',
      'PERSONAL_CARE_HAIR_AND_BEAUTY',
      'PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING',
      'PERSONAL_CARE_OTHER_PERSONAL_CARE',
    ],
  },
  {
    ledgeCategory: 'Home',
    primary: 'HOME_IMPROVEMENT',
    color: '#84CC16',
    icon: '🏠',
    subcategories: ['Furniture', 'Repairs'],
    detailedCodes: [
      'HOME_IMPROVEMENT_FURNITURE',
      'HOME_IMPROVEMENT_HARDWARE',
      'HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE',
      'HOME_IMPROVEMENT_SECURITY',
      'HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT',
    ],
  },
  {
    ledgeCategory: 'Services',
    primary: 'GENERAL_SERVICES',
    color: '#06B6D4',
    icon: '🧰',
    subcategories: ['Subscriptions', 'Insurance'],
    detailedCodes: [
      'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING',
      'GENERAL_SERVICES_AUTOMOTIVE',
      'GENERAL_SERVICES_CHILDCARE',
      'GENERAL_SERVICES_CONSULTING_AND_LEGAL',
      'GENERAL_SERVICES_EDUCATION',
      'GENERAL_SERVICES_INSURANCE',
      'GENERAL_SERVICES_POSTAGE_AND_SHIPPING',
      'GENERAL_SERVICES_STORAGE',
      'GENERAL_SERVICES_OTHER_GENERAL_SERVICES',
    ],
  },
  {
    ledgeCategory: 'Income',
    primary: 'INCOME',
    color: '#34D399',
    icon: '💰',
    subcategories: ['Paycheck', 'Interest'],
    detailedCodes: [
      'INCOME_WAGES',
      'INCOME_OTHER_INCOME',
      'INCOME_INTEREST_EARNED',
      'INCOME_DIVIDENDS',
      'INCOME_RETIREMENT_PENSION',
      'INCOME_TAX_REFUND',
      'INCOME_UNEMPLOYMENT',
    ],
  },
  {
    ledgeCategory: 'Transfers In',
    primary: 'TRANSFER_IN',
    color: '#2DD4BF',
    icon: '⬇️',
    subcategories: ['Zelle', 'Venmo'],
    detailedCodes: [
      'TRANSFER_IN_ACCOUNT_TRANSFER',
      'TRANSFER_IN_PEER_TO_PEER_PAYMENT',
      'TRANSFER_IN_CASH_ADVANCES_AND_LOANS',
      'TRANSFER_IN_DEPOSIT',
      'TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS',
      'TRANSFER_IN_SAVINGS',
      'TRANSFER_IN_OTHER_TRANSFER_IN',
    ],
  },
  {
    ledgeCategory: 'Transfers Out',
    primary: 'TRANSFER_OUT',
    color: '#9CA3AF',
    icon: '⬆️',
    subcategories: ['Zelle', 'Venmo'],
    detailedCodes: [
      'TRANSFER_OUT_ACCOUNT_TRANSFER',
      'TRANSFER_OUT_PEER_TO_PEER_PAYMENT',
      'TRANSFER_OUT_SAVINGS',
      'TRANSFER_OUT_WITHDRAWAL',
      'TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS',
      'TRANSFER_OUT_OTHER_TRANSFER_OUT',
    ],
  },
  {
    ledgeCategory: 'Loans',
    primary: 'LOAN_PAYMENTS',
    color: '#F87171',
    icon: '🏦',
    subcategories: ['Student Loans', 'Credit Card'],
    detailedCodes: [
      'LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT',
      'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',
      'LOAN_PAYMENTS_MORTGAGE_PAYMENT',
      'LOAN_PAYMENTS_CAR_PAYMENT',
      'LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT',
      'LOAN_PAYMENTS_OTHER_PAYMENT',
    ],
  },
  {
    ledgeCategory: 'Fees',
    primary: 'BANK_FEES',
    color: '#6B7280',
    icon: '⚠️',
    subcategories: [],
    detailedCodes: [
      'BANK_FEES_ATM_FEES',
      'BANK_FEES_FOREIGN_TRANSACTION_FEES',
      'BANK_FEES_INSUFFICIENT_FUNDS',
      'BANK_FEES_INTEREST_CHARGE',
      'BANK_FEES_OVERDRAFT_FEES',
      'BANK_FEES_OTHER_BANK_FEES',
    ],
  },
  {
    ledgeCategory: 'Other',
    primary: 'GOVERNMENT_AND_NON_PROFIT',
    color: '#71717A',
    icon: '❔',
    subcategories: [],
    detailedCodes: [
      'GOVERNMENT_AND_NON_PROFIT_DONATIONS',
      'GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES',
      'GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT',
      'GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT',
    ],
  },
]

export const ALL_PFC_DETAILED_CODES: string[] = DEFAULT_PFC_MAPPING.flatMap((e) => e.detailedCodes)
