plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/qihongwu/VSCode/tofi/oauth-redirect"
publishOrigin = "default"
base = "/Users/qihongwu/VSCode/tofi/oauth-redirect"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/.well-known/apple-app-site-association"

[headers.values]
Content-Type = "application/json"